name: Flutter Mobile CI

on:
  push:
    branches: [ main, master ]
    paths:
      - "medical_app/**"
      - ".github/workflows/flutter_build.yml"
  pull_request:
    branches: [ main, master ]
    paths:
      - "medical_app/**"
      - ".github/workflows/flutter_build.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build & Analyze Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        working-directory: ./medical_app
        run: flutter pub get

      - name: Run tests
        working-directory: ./medical_app
        run: flutter test

      - name: Run code analysis
        working-directory: ./medical_app
        run: flutter analyze

      - name: Build Android APK (Debug mode)
        working-directory: ./medical_app
        run: flutter build apk --debug

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: medical-app-apk
          path: medical_app/build/app/outputs/flutter-apk/app-debug.apk
